### ISSUE TITLE
feat: PhantomJS for PDFs in Quizzes

### ISSUE THREAD

**Issue by kristiyanivanovx** [kristiyanivanovx/WeLearn#44]

**Comment by jimmywarting** [comment]
PhantomJS is pretty much dead now.
It's a old headless browser that no real user have ever used and was solo created for developers to automate & scrape stuff.
it don't get any more updates and are now archived/suspended for a long time now

ppl should just stop using it and switch to something like puppeteer instead.

**Comment by kristiyanivanovx** [comment]
Thanks, I will look into it.

**Comment by kristiyanivanovx** [comment]
I ended up using `html2pdf.js`- https://ekoopmans.github.io/html2pdf.js/
